const fs = require('fs');
let html = fs.readFileSync('my-desk.html', 'utf8');

// 1. Add onclick handlers to the Match Report buttons
html = html.replace(/<button class="w-full bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600/g,
`<button onclick="showMatchReport()" class="w-full bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600`);

// 2. Add the modal before </body>
const modalHtml = `
    <!-- MATCH REPORT MODAL -->
    <div id="matchReportModal" class="fixed inset-0 z-[100] bg-slate-900/80 hidden flex-col items-center justify-center p-4 backdrop-blur-md animate-fade">
        <div class="bg-white dark:bg-slate-800 rounded-[32px] w-full max-w-md shadow-2xl relative overflow-hidden flex flex-col h-[85vh]">
            
            <!-- Header -->
            <div class="relative bg-gradient-to-r from-[#003DA5] to-blue-600 p-6 text-white shrink-0">
                <button onclick="closeMatchReport()" class="absolute top-4 right-4 w-8 h-8 bg-white/20 hover:bg-white/30 rounded-full flex items-center justify-center transition-colors">
                    <i class="fa-solid fa-xmark"></i>
                </button>
                <div class="flex items-center gap-4 mb-4">
                    <div class="w-16 h-16 rounded-2xl bg-white/20 flex flex-col items-center justify-center border-2 border-white/50 shadow-inner">
                        <span class="text-2xl font-black leading-none">92<span class="text-sm">%</span></span>
                    </div>
                    <div>
                        <h2 class="text-xl font-black italic tracking-tighter uppercase leading-none lang-en">Match Report</h2>
                        <h2 class="text-xl font-black italic tracking-tighter uppercase leading-none lang-es hidden">Reporte de Coincidencia</h2>
                        <p class="text-[10px] font-bold uppercase opacity-80 mt-1">Generated by NEXUS AI</p>
                    </div>
                </div>
                <div class="flex justify-between items-end">
                    <div>
                        <p class="text-[9px] uppercase font-black opacity-80 mb-0.5">Buyer</p>
                        <p class="text-sm font-bold">Invest Corp (Escazú)</p>
                    </div>
                    <div class="text-right">
                        <p class="text-[9px] uppercase font-black opacity-80 mb-0.5">Property</p>
                        <p class="text-sm font-bold">Luxury Condo Unit 4B</p>
                    </div>
                </div>
            </div>

            <!-- Scrollable Content -->
            <div class="p-6 overflow-y-auto flex-1 bg-slate-50 dark:bg-slate-900/50 space-y-6 hidden-scrollbar">
                
                <!-- Match Breakdown -->
                <div class="space-y-4">
                    <h3 class="text-xs font-black text-slate-400 uppercase tracking-widest lang-en">Criteria Breakdown</h3>
                    <h3 class="text-xs font-black text-slate-400 uppercase tracking-widest lang-es hidden">Desglose de Criterios</h3>
                    
                    <div class="space-y-3">
                        <!-- Budget -->
                        <div>
                            <div class="flex justify-between text-[10px] font-black uppercase mb-1">
                                <span class="text-slate-700 dark:text-slate-300"><i class="fa-solid fa-money-bill-wave text-green-500 mr-1"></i> Budget / Presupuesto</span>
                                <span class="text-green-500">100% Match</span>
                            </div>
                            <div class="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                                <div class="h-full bg-green-500 w-full rounded-full"></div>
                            </div>
                            <p class="text-[9px] text-slate-500 font-bold mt-1">Buyer max: $450k | Property: $425k</p>
                        </div>
                        
                        <!-- Location -->
                        <div>
                            <div class="flex justify-between text-[10px] font-black uppercase mb-1">
                                <span class="text-slate-700 dark:text-slate-300"><i class="fa-solid fa-location-dot text-blue-500 mr-1"></i> Area / Zona</span>
                                <span class="text-blue-500">100% Match</span>
                            </div>
                            <div class="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                                <div class="h-full bg-blue-500 w-full rounded-full"></div>
                            </div>
                            <p class="text-[9px] text-slate-500 font-bold mt-1">Exact match: Escazú</p>
                        </div>
                        
                        <!-- Specs -->
                        <div>
                            <div class="flex justify-between text-[10px] font-black uppercase mb-1">
                                <span class="text-slate-700 dark:text-slate-300"><i class="fa-solid fa-bed text-amber-500 mr-1"></i> Specs / Especificaciones</span>
                                <span class="text-amber-500">80% Match</span>
                            </div>
                            <div class="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                                <div class="h-full bg-amber-500 w-[80%] rounded-full"></div>
                            </div>
                            <p class="text-[9px] text-slate-500 font-bold mt-1">Property has 2 beds (Buyer requested 2-3 beds)</p>
                        </div>
                        
                        <!-- Amenities -->
                        <div>
                            <div class="flex justify-between text-[10px] font-black uppercase mb-1">
                                <span class="text-slate-700 dark:text-slate-300"><i class="fa-solid fa-swimming-pool text-purple-500 mr-1"></i> Amenities / Amenidades</span>
                                <span class="text-purple-500">85% Match</span>
                            </div>
                            <div class="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                                <div class="h-full bg-purple-500 w-[85%] rounded-full"></div>
                            </div>
                            <p class="text-[9px] text-slate-500 font-bold mt-1">Missing: Private Garden (Has Shared Green Area)</p>
                        </div>
                    </div>
                </div>

                <!-- Missing Elements / Warnings -->
                <div class="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-700/50 p-4 rounded-2xl">
                    <h4 class="text-[10px] font-black text-amber-600 dark:text-amber-500 uppercase tracking-widest mb-2 flex items-center gap-1.5">
                        <i class="fa-solid fa-triangle-exclamation"></i> NEXUS Insights
                    </h4>
                    <p class="text-[10px] text-amber-800 dark:text-amber-400 font-bold leading-relaxed">
                        The buyer strongly requested a <span class="font-black italic">private garden</span> which this property lacks. However, the exact location match and being 5% under budget makes it a highly viable option. Mention this cost savings in your pitch!
                    </p>
                </div>

                <!-- Action Areas -->
                <div class="grid grid-cols-2 gap-3">
                    <button class="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-3 rounded-2xl text-center shadow-sm hover:border-[#003DA5] transition-colors group">
                        <i class="fa-solid fa-file-pdf text-red-500 text-lg mb-1 group-hover:scale-110 transition-transform"></i>
                        <p class="text-[9px] font-black text-slate-600 dark:text-slate-300 uppercase">Export PDF</p>
                    </button>
                    <button class="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 p-3 rounded-2xl text-center shadow-sm hover:border-[#003DA5] transition-colors group">
                        <i class="fa-solid fa-share-nodes text-blue-500 text-lg mb-1 group-hover:scale-110 transition-transform"></i>
                        <p class="text-[9px] font-black text-slate-600 dark:text-slate-300 uppercase">Share Report</p>
                    </button>
                </div>

            </div>

            <!-- Footer Action -->
            <div class="p-4 bg-white dark:bg-slate-800 border-t border-slate-100 dark:border-slate-700 shrink-0">
                <a href="https://wa.me/50688888888" target="_blank" class="w-full bg-[#25D366] text-white py-4 rounded-2xl font-black uppercase text-xs shadow-lg hover:shadow-xl transition-all active:scale-95 flex items-center justify-center gap-2">
                    <i class="fa-brands fa-whatsapp text-lg"></i> <span class="lang-en">Contact Counterpart</span><span class="lang-es hidden">Contactar Contraparte</span>
                </a>
            </div>

        </div>
    </div>

    <script>
        function showMatchReport() {
            document.getElementById('matchReportModal').classList.remove('hidden');
            document.getElementById('matchReportModal').classList.add('flex');
        }
        function closeMatchReport() {
            document.getElementById('matchReportModal').classList.add('hidden');
            document.getElementById('matchReportModal').classList.remove('flex');
        }
    </script>
</body>`;

html = html.replace(/<\/body>/, modalHtml);
fs.writeFileSync('my-desk.html', html, 'utf8');
